### ISSUE TITLE
Suggestion-product positioning and solution description

### ISSUE THREAD

**Issue by zendwind** [Tencent/TBase#10]
1. Product Positioning: I have a little doubt about this product positioning, if it is for users around the world, the introduction in index page (README.md) should be more professional, which do not mix English and Chinese description together, and consider more from user's perspectives.

2. Solution: The official website (tbase.qq.com) hasn't been updated since 2017, I see there are many customers using it . So I hope the website can see more customer's solution and let more people to know what TBase can do and How to introduce TBase in their businesses.

Thank you

**Comment by weily1** [comment]
> 1. Product Positioning: I have a little doubt about this product positioning, if it is for users around the world, the introduction in index page (README.md) should be more professional, which do not mix English and Chinese description together, and consider more from user's perspectives.
> 2. Solution: The official website (tbase.qq.com) hasn't been updated since 2017, I see there are many customers using it . So I hope the website can see more customer's solution and let more people to know what TBase can do and How to introduce TBase in their businesses.
> 
> Thank you

Thank you for your professional advice. These are very helpful to us. We will optimize our official website  and documentation as soon as possible. We also expect more people to participate in the open source work of TBase.

**Comment by yazun** [comment]
Would it be possible to have Postgres-XL-like documentation? - with pure Postgres documentation and only deviations from PG-XL being described with a special formatting?
My understanding is that such documentation does not exist at the moment?

**Comment by JennyJennyChen** [comment]
https://github.com/Tencent/TBase/wiki
