### ISSUE TITLE
create node dn01 with (type=datanode,host='10.0.1.110',port=23001,primary=false,preferred=false);

### ISSUE THREAD

**Issue by samsung0-cpu** [Tencent/TBase#101]
ERROR:  PGXC Node name dn01 cluster tbase_cluster must be defined in ascii order existing node name dn02 cluster tbase_cluster

**Comment by JennyJennyChen** [comment]
错误提示说的比较清楚了，节点名字必须按照ASCII码顺序定义，你现在已经有dn02那，那么下一个应该是dn03，不能是dn01
