### ISSUE TITLE
Status of Foreign Data Wrapper support.

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#102]
Hello,
XL did not allow for FDW creation - has anything changed for TBase? - I saw some code in fdw parts has changed..
i.e. https://github.com/Tencent/TBase/commit/6b440a79956653a382210e675233b2df4145131c merged some optimizations for FWDs.

**Comment by JennyJennyChen** [comment]
tbase currently does not support FDW, but will support it in the future, so developers also consider compatibility when coding, so there will be some in the code
