### ISSUE TITLE
Acknowledgment of TBase: thank you from European Space Agency Gaia Group in Geneva, Switzerland

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#104]
Dear TBase community,

I would like to share our thank you for your support and keeping full-blown MPP DBMS based on Postgres alive! 

Since we accomplished a major goal for ESA [Gaia Data Release 3 ](https://www.cosmos.esa.int/web/gaia/release) (DR3) to be published next year, on behalf of Gaia Geneva, I would like to stress that **TBase has been a crucial component for our data analysis during this year and it will be officially acknowledged in the already one of the most successful astronomy projects of all time!**

We made a switchover from Postgres-XL earlier this year and we plan to use it til the end of the mission in 2026 and beyond.

I created this thread to post information that might be of your interest, with mentions of TBase in our outreach and how we could increase its recognition together.

**Comment by yazun** [comment]
The presentation slides mentioning TBase, that was given in June 2021 during European Astronomical Society [EAS2021](https://eas.unige.ch/EAS2021/): probably one of the biggest astronomy conferences (2500 attendees), 

Can be found here:
[GaiaVari platform](https://gaiaowncloud.isdc.unige.ch/index.php/s/WFwvjX3QmPD0xQw)

The video on the conference website should be available in later time as well.

Krzysztof

**Comment by JennyJennyChen** [comment]
Thank you very much for your recognition. It is our honor to be able to help such an important astronomy project. We will continue to work hard to make TBase open source better and provide better services for more projects. If you have any questions or more functional requirements during use, you can contact us at any time.
