### ISSUE TITLE
执行monitor all查看集群状态时，显示gtmslave是Not running

### ISSUE THREAD

**Issue by Wanq989525** [Tencent/TBase#107]
初始化集群后，执行monitor all查看集群，发现gtmslave是Not running，执行gtm_ctl status -P 备gtmport -H 备gtmip，发现gtmslave是存活的。多次实验结果相同。注：环境中的防火墙和selinux均已关闭。
![image](https://user-images.githubusercontent.com/32434243/131438084-118fe355-8c82-4d71-a38c-23318ab48b3c.png)
![image](https://user-images.githubusercontent.com/32434243/131438113-8db8eda6-6677-4e4b-943f-e1d9a3265bd9.png)
![image](https://user-images.githubusercontent.com/32434243/131438126-30e03e8a-b5c4-43f4-863f-c60ad8a7401e.png)

**Comment by JennyJennyChen** [comment]
已解决，参考commit： https://github.com/Tencent/TBase/commit/c47bebc338b01177687a3a4060d61b235bf2c03f
