### ISSUE TITLE
请问哪里有使用文档之类的？

### ISSUE THREAD

**Issue by waters321** [Tencent/TBase#11]
https://tbase.qq.com/ 注册不了，一直提示验证码错误
文档也不让匿名下载，搭建好了如何用....

**Comment by SenHuSelf** [comment]
> https://tbase.qq.com/ 注册不了，一直提示验证码错误
> 文档也不让匿名下载，搭建好了如何用....

文档后续很快就会放出来了，请稍等几天

**Comment by JennyJennyChen** [comment]
https://github.com/Tencent/TBase/wiki
这里有详细的文档
