### ISSUE TITLE
make -sj时报 error   redefinition

### ISSUE THREAD

**Issue by weipengffk** [Tencent/TBase#12]
GTM_ThreadInfo 

![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)

**Comment by SenHuSelf** [comment]
> GTM_ThreadInfo
> 
> ![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)

什么平台编译的，以及configure参数和编译命令是什么？

**Comment by weipengffk** [comment]
linux系统，CentOS release 6.8 (Final);就是按照官网编译的。

chmod +x configure*    
mkdir /com/lcsc/apps/tbase_bin_v2.0
./configure --prefix=/com/lcsc/apps/tbase_bin_v2.0  --enable-user-switch --with-openssl  --with-ossp-uuid CFLAGS=-g
 make clean
 make -sj  ；这一步异常

**Comment by weipengffk** [comment]
> > GTM_ThreadInfo
> > ![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)
> 
> 什么平台编译的，以及configure参数和编译命令是什么？

linux，CentOS6.8；  按照文档   make -sj时异常。

**Comment by weipengffk** [comment]
> > GTM_ThreadInfo
> > ![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)
> 
> 什么平台编译的，以及configure参数和编译命令是什么？

可能跟我下master有关，我去下release试下

**Comment by SenHuSelf** [comment]
> > > GTM_ThreadInfo
> > > ![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)
> > 
> > 
> > 什么平台编译的，以及configure参数和编译命令是什么？
> 
> linux，CentOS6.8； 按照文档 make -sj时异常。

看一下gcc版本是多少，如果低于4.6，升级到4.6或以上版本，试试

**Comment by weipengffk** [comment]
> > > > GTM_ThreadInfo
> > > > ![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)
> > > 
> > > 
> > > 什么平台编译的，以及configure参数和编译命令是什么？
> > 
> > 
> > linux，CentOS6.8； 按照文档 make -sj时异常。
> 
> 看一下gcc版本是多少，如果低于4.6，升级到4.6或以上版本，试试

gcc升级到 gcc 6.4.0后，仍然有问题。不过报这个
make error: undefined reference to `Recovery_IsStandby’
![20191113203039](https://user-images.githubusercontent.com/13691836/68763958-b0b6a200-0654-11ea-9692-7f1018de565c.jpg)

**Comment by SenHuSelf** [comment]
> > > > > GTM_ThreadInfo
> > > > > ![54ab2ba263396cbf12187e998fa1879](https://user-images.githubusercontent.com/13691836/68639615-16653a00-0540-11ea-8a7f-e7980607fef3.jpg)
> > > > 
> > > > 
> > > > 什么平台编译的，以及configure参数和编译命令是什么？
> > > 
> > > 
> > > linux，CentOS6.8； 按照文档 make -sj时异常。
> > 
> > 
> > 看一下gcc版本是多少，如果低于4.6，升级到4.6或以上版本，试试
> 
> gcc升级到 gcc 6.4.0后，仍然有问题。不过报这个
> make error: undefined reference to `Recovery_IsStandby’
> ![20191113203039](https://user-images.githubusercontent.com/13691836/68763958-b0b6a200-0654-11ea-9692-7f1018de565c.jpg)

这个应该是跟函数定义有关，把inline去掉试试

**Comment by weipengffk** [comment]
。。。。等我后面学习C++再来调研
