### ISSUE TITLE
tbase 密码只要不为空，随便写都能登录

### ISSUE THREAD

**Issue by tiancai45** [Tencent/TBase#122]
我现在密码随便写，只要不为空就可以登录。有点不安全呀。大佬们

**Comment by tiancai45** [comment]
![RDF2BO7II4XSLCU IHE}LGX](https://user-images.githubusercontent.com/25494095/150975439-374b3f27-b559-46f1-bc34-a015e2a9955c.png)

**Comment by tiancai45** [comment]
![J98(RLE4J KOZCP)A1{157D](https://user-images.githubusercontent.com/25494095/150975785-f8bd7f02-16d0-4125-8452-058f18edb7b2.png)

**Comment by tiancai45** [comment]
我改过密码了，密码这个参数就好像没使用一样。写不写都会连接成功

**Comment by JennyJennyChen** [comment]
那是因为你配置了这个节点为授信节点，进入了无密码访问模式，可以了解一下PG的pg_hba.conf

**Comment by tiancai45** [comment]
哦，我懂了，谢谢
