### ISSUE TITLE
Foreign Key on replicated tables

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#123]
In the past we patched XL to enable FKs between the replicated tables. 
We see there's a check preventing FKs on replicated tables based on _PG_REGRESS_ define.

https://github.com/Tencent/TBase/blob/master/src/backend/commands/tablecmds.c#L8841

Could you explain if we could change this check to allow FKs between replicated tables only (we never had problem with them in the past, also combined with recursive CTE).
Thank you

**Comment by JennyJennyChen** [comment]
Other colleagues  may add this code just to want to limit the data writing of the replicated table to only consider this node, and not care about other nodes to enhance the performance of data writing.

**Comment by yazun** [comment]
Could this be enabled with the compaile switch?

**Comment by JennyJennyChen** [comment]
Regarding the reason for prohibiting the foreign key on the replication table, I consulted the relevant personnel. The main reason is that there can be no triggers on the replication table, and the foreign keys in the PG are also implemented by triggers, so the foreign keys are also prohibited.
If you are sure that you are not using triggers on the replicated table, you can remove this if statement in the source code and recompile the new bin to solve:
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/48546628/158100909-bdba902f-cd72-41e6-b804-e0904062851f.png">

**Comment by yazun** [comment]
So the question emerges why we could not have triggers on the replicated table, granted such triggers would not use anything distributed?
It seems it would be consistent with other limitations coming from distribution, maybe a GUC allowing for this would make sense?

**Comment by JennyJennyChen** [comment]
The replication table is that all DN nodes have full data about this table, and all DN nodes will perform operations on this data. Then suppose that there is a trigger on this replicated table: when inserting data, add the inserted data to another non-replicated table, then this non-replicated table will have N pieces of data (N is the number of DN nodes).

Triggers can be used in distributed systems, but replication tables cannot be used, shard tables can be used.
