### ISSUE TITLE
tabse怎么更新软件版本,并保留数据

### ISSUE THREAD

**Issue by tiancai45** [Tencent/TBase#124]
tabse怎么更新软件版本,并保留数据.
现在只能备份.再导入.
有别的方法吗?

**Comment by tiancai45** [comment]
谢谢大佬

**Comment by JennyJennyChen** [comment]
1、开源的升级到2.3.0需要备份再导入，其他版本直接替换bin包（为保险起见，建议先保存原来的bin，然后再操作以备出问题了回滚）
2、商业版本另说
