### ISSUE TITLE
至今还在PostgreSQL10的级别。TBase有考虑升级吗？

### ISSUE THREAD

**Issue by blusewang** [Tencent/TBase#131]
看到`TBase`就是从`Postgres-XL`克隆过来的。`Postgres-XL`从`PG10`开始停更。`TBase`也就停留在`PG10`直到今天。
`TBase`有考虑支持到`PG14`吗？

**Comment by JennyJennyChen** [comment]
TBase的迭代升级方法并没有采用整个PG完整升级，而是结合实际需求合并升级某一部分功能到新版本，比如现在的V2.3.0已经具备PG12分区表的功能，后续如果有其他部分的新特性需求也会采用次方式。
