### ISSUE TITLE
postgres迁移到TBase时uuid类型的字段如何处理？

### ISSUE THREAD

**Issue by childewuque** [Tencent/TBase#133]
从已有的pg库导出DDL，有一些表有uuid类型的字段，比如：
CREATE TABLE version (rule_id uuid NOT NULL  PRIMARY KEY,description character varying(255) )
 
最新版的tbase，部署好后，通过psql 导入DDL，会报错：   ERROR:  Column rule_id is not a shard distributable data type
从TBASE的角度看，有什么办法解决吗？--不要修改已有的数据，因为这个uuid字段的内容，在多个表也有用到，想平滑的迁移数据过来

**Comment by runewrz** [comment]
`CREATE TABLE version (rule_id uuid NOT NULL PRIMARY KEY,description character varying(255) ) 
`
这里默认使用rule_id作为分布键，但目前不支持uuid类型作为分布键，可以使用varchar(36)来存储uuid字符串，不使用uuid类型，后续有计划支持该特性。
