### ISSUE TITLE
audit_admin user cannot execute ‘audit all;’ in md5 authenrization.

### ISSUE THREAD

**Issue by hnusttyj530** [Tencent/TBase#145]
postgres=# \c - audit_admin
Password for user audit_admin:
FATAL:  password authentication failed for user "audit_admin"
Previous connection kept

**Comment by hnusttyj530** [comment]
/*
 * Builds up a connection string
 */
char *
PGXCNodeConnStr(char *host, int port, char *dbname,
                char *user, char *pgoptions, char *remote_type, char *parent_node)
{// #lizard forgives
    char       *out,
                connstr[1024];
    int            num;
#ifdef __TBASE__
    bool       same_host = false;

    if (host && (strcmp(PGXCNodeHost, host) == 0))
    {
        same_host = true;
    }
#endif
    /*
     * Build up connection string
     * remote type can be Coordinator, Datanode or application.
     */
#ifdef _MLS_
    if (strcmp(user, MLS_USER) == 0 || strcmp(user, AUDIT_USER))
    {
        if (same_host)
        {
            num = snprintf(connstr, sizeof(connstr),
                   "port=%d dbname=%s user=%s application_name='pgxc:%s' sslmode=disable options='-c remotetype=%s -c parentnode=%s %s %s'",
                   port, dbname, user, parent_node, remote_type, parent_node,
                   pgoptions, MLS_CONN_OPTION);
        }

change ：


/*
 * Builds up a connection string
 */
char *
PGXCNodeConnStr(char *host, int port, char *dbname,
                char *user, char *pgoptions, char *remote_type, char *parent_node)
{// #lizard forgives
    char       *out,
                connstr[1024];
    int            num;
#ifdef __TBASE__
    bool       same_host = false;

    if (host && (strcmp(PGXCNodeHost, host) == 0))
    {
        same_host = true;
    }
#endif
    /*
     * Build up connection string
     * remote type can be Coordinator, Datanode or application.
     */
#ifdef _MLS_
    if (strcmp(user, MLS_USER) == 0 || strcmp(user, AUDIT_USER)==0)
    {
        if (same_host)
        {
            num = snprintf(connstr, sizeof(connstr),
                   "port=%d dbname=%s user=%s application_name='pgxc:%s' sslmode=disable options='-c remotetype=%s -c parentnode=%s %s %s'",
                   port, dbname, user, parent_node, remote_type, parent_node,
                   pgoptions, MLS_CONN_OPTION);
        }

**Comment by runewrz** [comment]
You need to ensure that all the CN DN GTM nodes' IP addresses are in trust method in pg_hba.conf cause the connection between nodes uses trust method.
