### ISSUE TITLE
tbase 支持列存储吗？

### ISSUE THREAD

**Issue by titati78** [Tencent/TBase#15]
PG 默认只有heap表行存储，tbase 可以支持列存储吗？
似乎代码里没看到

谢谢

**Comment by JennyJennyChen** [comment]
@titati78 TBase支持的，不过不在当前开源的版本中

**Comment by titati78** [comment]
开源版本，和商用版本，有哪些差别呢？
有哪些企业功能，在开源版本里没有呢？
或者 有哪些企业级功能在开源版本里呢？

**Comment by caseykwang** [comment]
> 开源版本，和商用版本，有哪些差别呢？
> 有哪些企业功能，在开源版本里没有呢？
> 或者 有哪些企业级功能在开源版本里呢？

开源版本主要是开源的数据库内核，商用版本还包括操作维护系统，例如说告警、监控、话统等等，但开源的数据库内核的功能都是完备的。

之前提到的列存特性，这个主要是仍然在开发测试阶段，等成熟之后再进行开源。

**Comment by yjhjstz** [comment]
什么时候开源呢？

**Comment by JennyJennyChen** [comment]
> 什么时候开源呢？

多谢关注，列存暂时没有开源计划
