### ISSUE TITLE
Build Error: Multiple Definition

### ISSUE THREAD

**Issue by williamxiongwei** [Tencent/TBase#150]
I meet problem while compiling TBase:
/usr/bin/ld: gtm_proxy_opt.o:/home/tbase-2.4/TBase/src/gtm/proxy/gtm_proxy_opt.c:78: multiple definition of `GTMConfigFileName'; proxy_main.o:/home/tbase-2.4/TBase/src/gtm/proxy/proxy_main.c:134: first defined here.

System: OpenEuler
Please help me solve this.
Thanks.

**Comment by runewrz** [comment]
The reason for the compilation failure may be that a higher version of the compiler is used.
The solution is mentioned in problem 2 of this issue https://github.com/Tencent/TBase/issues/134
