### ISSUE TITLE
从一开始pgxz出来就关注很久了终于开源了，请尽快将文档开放吧

### ISSUE THREAD

**Issue by wzfxue** [Tencent/TBase#19]
之前用pgxl一段时间做测试，始终不敢用到生产环境，请问tbase用于生产环境（OLTP）是否完全可行？
tbase.qq.com看描述中好像有后台管理页面，请问如何开启访问？

**Comment by weily1** [comment]
> 之前用pgxl一段时间做测试，始终不敢用到生产环境，请问tbase用于生产环境（OLTP）是否完全可行？
> tbase.qq.com看描述中好像有后台管理页面，请问如何开启访问？

TBase定位是70%的OLTP，30%的OLAP场景。目前开源的是稳定版本，经过了一年多的检验，目前运营的实例有几十个，内核稳定性这块儿还是值得信赖的，你可以试用一下，期待你的反馈。

后台管理页面我理解你说的是TBase OSS管控系统，目前这块儿没有开源计划。

**Comment by yazun** [comment]
Hello,
Are English speakers welcome in the group?

**Comment by jerome-peng** [comment]
二维码过期了，大佬!

**Comment by jerome-peng** [comment]
> Hello,
> Are English speakers welcome in the group?

tbase welcome you

**Comment by JennyJennyChen** [comment]
https://github.com/Tencent/TBase/wiki
