### ISSUE TITLE
有微信或者qq讨论群吗？

### ISSUE THREAD

**Issue by whf307** [Tencent/TBase#20]

**Comment by weily1** [comment]
![image](https://user-images.githubusercontent.com/57513714/69533857-987b4700-0fb3-11ea-948e-8e32a86a929e.png)

这个是TBase微信官方讨论群的二维码，欢迎扫码加入

**Comment by whf307** [comment]
满100人了需要拉一下。。

**Comment by SayHelloBriggs** [comment]
> ![image](https://user-images.githubusercontent.com/57513714/69533857-987b4700-0fb3-11ea-948e-8e32a86a929e.png)
> 
> 这个是TBase微信官方讨论群的二维码，欢迎扫码加入

二维码过期了 是否可以再来一个？

**Comment by ghzj0615** [comment]
同求

**Comment by samcaicn** [comment]
![image](https://user-images.githubusercontent.com/3318094/71349271-93f18080-25a9-11ea-82b5-c185350fc6ec.png)

**Comment by samcaicn** [comment]
成都的亲们来这里一起学习tbase撒，如果二维码过期就加我微信526218543

**Comment by WallXue** [comment]
> ![image](https://user-images.githubusercontent.com/57513714/69533857-987b4700-0fb3-11ea-948e-8e32a86a929e.png)
> 
> 这个是TBase微信官方讨论群的二维码，欢迎扫码加入

大佬 拉我一下 群   vx：blazeday

**Comment by JennyJennyChen** [comment]
https://github.com/Tencent/TBase/wiki  wiki首页这里的二维码可以扫描申请加入，申请时请备注： tbase
