### ISSUE TITLE
wiki和#20里面的二维码过期了

### ISSUE THREAD

**Issue by SayHelloGsx** [Tencent/TBase#24]
麻烦大佬能否再发个群二维码啊 感谢！

**Comment by samcaicn** [comment]
![image](https://user-images.githubusercontent.com/3318094/71349254-89cf8200-25a9-11ea-92d2-b934ea885488.png)

**Comment by samcaicn** [comment]
成都的亲们来这里一起学习tbase撒，如果二维码过期就加我微信526218543

**Comment by samcaicn** [comment]
![image](https://user-images.githubusercontent.com/3318094/71879569-53793180-3169-11ea-9931-60d056d439f5.png)

**Comment by JennyJennyChen** [comment]
https://github.com/Tencent/TBase/wiki
