### ISSUE TITLE
查询异常：latch already owned

### ISSUE THREAD

**Issue by grapelet520** [Tencent/TBase#25]
在执行查询时有时会抛出异常或卡住无法取消请求：
`ERROR:  node:dn004, backend_pid:32570, nodename:dn004,backend_pid:32570,message:node:dn002, backend_pid:16921, nodename:dn002,backend_pid:16921,message:Failed to read from SQueue p_1_3c93_9_58a551eb, consumer (node 3, pid 16921, status 2) - CONSUMER_ERROR set, err_msg "node:dn004, backend_pid:32522, nodename:dn001,backend_pid:29990,message:latch already owned",,`
SQL语句：
```
select 
		vssd.f_stationcode,
		SUM(f_passenger) f_passenger,
		SUM(f_nodenumber) f_nodenumber 
from 
		(
			select 
					f_guid,
					f_stationcode,
					f_passenger 
			from 
					v_sendschedule
			where 	f_date='2018-12-01'
		)vss,
		(
			select 
					f_parentid,
					f_stationcode,
					SUM(f_nodenumber) f_nodenumber 
			from 
					v_sendschedule_detail
			where 	f_date='2018-12-01'
			group by f_stationcode,f_parentid
		) vssd
where 	vssd.f_parentid=vss.f_guid and vssd.f_stationcode=vss.f_stationcode
group by vssd.f_stationcode;
```
其中：
v_sendschedule记录数：19163112
v_sendschedule_detail记录数：48369630

**Comment by SuCuicui** [comment]
如果可以的话，麻烦提供一下表结构信息，还有尽量详细的复现信息，方便问题定位，谢谢

**Comment by mikewhb** [comment]
麻烦提供下 explain verbose  信息

**Comment by izoyo** [comment]
> 如果可以的话，麻烦提供一下表结构信息，还有尽量详细的复现信息，方便问题定位，谢谢

在进行 tpc-ds 3.0 测试时候也遇到了

**Comment by yazun** [comment]
We see another issue closed without any explanation. Maybe you should just comment as won't fix?
We offered to share the tpc-h code in https://github.com/Tencent/TBase/issues/149
