### ISSUE TITLE
编译出现unused variable告警

### ISSUE THREAD

**Issue by joanhh** [Tencent/TBase#26]
环境：
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
TBase: https://github.com/Tencent/TBase

编译步骤：
./configure --prefix=${INSTALL_PATH}/tbase_bin_v2.0 --enable-user-switch --with-openssl --with-ossp-uuid CFLAGS=-g
make clean
make -sj

告警信息：
![warnming](https://user-images.githubusercontent.com/54398322/70873567-3d080c00-1fe9-11ea-993e-60fbaf887d2e.png)

**Comment by whf307** [comment]
./configure --prefix=${INSTALL_PATH}/tbase_bin_v2.0 --enable-user-switch --with-openssl --with-ossp-uuid CFLAGS=-g


INSTALL_PATH这个环境变量你替换成实际的了么。

**Comment by joanhh** [comment]
我export INSTALL_PATH=实际路径

**Comment by runewrz** [comment]
能正常编译可以忽略warning信息。
