### ISSUE TITLE
pgloader做表迁移时报错

### ISSUE THREAD

**Issue by windtalkerbj** [Tencent/TBase#27]
在使用pgloader做mysql->TBASE的数据迁移测试时，在标准PG上未遇到问题；
在TBASE上，pgloader提示错误如下：
create temp table reloids(oid) as 
values ('public.yxhscs_itf_contract_validated'::regclass)
> ERROR:  Cannot support distribute type: RoundRobin

该SQL由pgloader工具发出，请问可以增加对这种临时表的支持吗？pgloader在一键迁移/持续化迁移MYSQL数据到PG上时很好用

**Comment by whf307** [comment]
TBase是分布式的，默认不指定的话第一个列作为分布键。regclass这种作为分布键，不支持吧。具体这样可以根据需求再改一下呢
