### ISSUE TITLE
TBase目前只开源这一个版本吗，有对应的版本号吗

### ISSUE THREAD

**Issue by huopaopao** [Tencent/TBase#3]
现在开源的TBase版本号是多少呢？没有见tag标签

**Comment by thomasdba** [comment]
应该是对应10

**Comment by qiuyuhang** [comment]
看configure.in是 10beta3 (Postgres-XL 10alpha2)

**Comment by JennyJennyChen** [comment]
@huopaopao 你好，当前开源的TBase v2.0版本，是基于PG10开发的，后续会持续迭代开源版本，tag标签这边已经打上了。
