### ISSUE TITLE
meaning of __SUPPORT_DISTRIBUTED_TRANSACTION__ and other params from pg_config_manual.h

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#31]
Hello,

First, very impressive changes in comparison to Postgres-XL!

Could you explain what's the idea behind TBase specific defines and code defined in pg_config_manual.h?
  i.e.
 __SUPPORT_DISTRIBUTED_TRANSACTION__  
 __COLD_HOT__
__STORAGE_SCALABLE__

There's clearly some code activated by them, but we would appreciate some small explanations. 
Also why these are disabled - is the code not trustworthy yet?

Thank you.
Krzysztof Nienartowicz

**Comment by Jasonysli** [comment]
SUPPORT_DISTRIBUTED_TRANSACTION means use global timestamp as data version,  this only can be true. COLD_HOT means enable cold hot data storage feature, this also only can be  true;STORAGE_SCALABLE means enable a new storage engine which has been removed from TBase, so this parameter should be disabled.
Sorry for the confusing parameters, maybe we should remove  these parameters, to make code easy to read.
