### ISSUE TITLE
Does coordinator take statistics from its preferred node only?

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#32]
This has been the situation with XL currently.
Has TBase changed the logic and statistics are merged from all datanodes or
 `analyze (coordinator) ..` is still needed to propagate statistics to all coordinators?

Thanks,
Krzysztof

**Comment by SuCuicui** [comment]
In the current code, coordinator pulls statistics result from all datanodes and merges them.
We will improve this part in the next release coming soon.  Please stay tuned.
