### ISSUE TITLE
Is global_snapshot_source='coordinator' supported?

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#38]
Looks like it causes xid to be always 0, no matter if set on coordinator or datanode renders system unusable with messages like 
```
ERROR:  XX000: start timestamp 0 is too old to execute, recentCommitTs 1840649352
```

**Comment by Jasonysli** [comment]
No， global_snapshot_source option is not supported any more!

**Comment by yazun** [comment]
Yes, it took us some time to understand this! Thanks for confirming!
