### ISSUE TITLE
能否发布一些关于集群加入节点, 删除节点等集群管理的文档?

### ISSUE THREAD

**Issue by wonght** [Tencent/TBase#46]
另外, 集群加入新的DN节点后, 数据会自动rebalance么?

**Comment by wonght** [comment]
group以及sharding表的信息的维护命令是什么? 新增节点后, 如何加入到group

**Comment by ludongyuan** [comment]
我也有同样的问题，你解决了吗？

**Comment by wonght** [comment]
还没有, 有的社群说开源版不提供动态扩展功能, 等待这里的官方解答

**Comment by JennyJennyChen** [comment]
这部分功能是通过管控系统来完成的，管控系统暂时不开源
