### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/TBase#48]
Stream is opened
https://github.com/Tencent/TBase/blob/3295393cbabd6f17676c53078cf4cc03aa9dc1fd/src/bin/confmod/confmod.c#L236

Opened file never closed
https://github.com/Tencent/TBase/blob/3295393cbabd6f17676c53078cf4cc03aa9dc1fd/src/bin/confmod/confmod.c#L255

**Comment by JennyJennyChen** [comment]
g_confpf is a global variable, here it is only responsible for opening, other places are responsible for using it, it will be closed after use, so there is no resource leakage problem

**Comment by JennyJennyChen** [comment]
function  "create_new_conf_file" to be  closed the g_confpf
