### ISSUE TITLE
pgxc_node_str() function is broken (XL regression)

### ISSUE THREAD

**Issue by yazun** [Tencent/TBase#52]
Returns pointer as function is thinking GUC being returned is varlena.
XL has proper implementation..

**Comment by JennyJennyChen** [comment]
Can you provide detailed information ？(for example: expectations, actual conditions, comparison with PGXL, etc.)

**Comment by yazun** [comment]
It was not returning expected results (garbage): fix is here https://github.com/yazun/TBase/commit/31ea61bb4ea15d778456c46bcd20694425b589c3

**Comment by JennyJennyChen** [comment]
Thanks for your fix
