### ISSUE TITLE
why global and local gts not sync !!! 

### ISSUE THREAD

**Issue by ypma** [Tencent/TBase#56]
postgres=# select * from pgxc_node;
ERROR:  global gts:3081548147 is earlier than local gts:3387238789, please check GTM status!

**Comment by Jasonysli** [comment]
This should never happen, can you support the gtm.log so we can see what happen on GTM?

**Comment by ypma** [comment]
the problem has already been solved ,   I didn't install it correctly .
Thanks .

**Comment by JennyJennyChen** [comment]
the problem has already been solved
