### ISSUE TITLE
支持ibatis/jpa这样的中间件吗

### ISSUE THREAD

**Issue by luyongfugx** [Tencent/TBase#58]
支持ibatis/jpa这样的中间件吗？

**Comment by wzfxue** [comment]
你这问题就和问是否支持jdbc有何区别？

**Comment by githubMJ** [comment]
TBase这两个ORM框架都是支持的，和Postgresql的使用方法一样，比如jpa在使用的时候只要将方言切换成Postgresql的方言之后都可以兼容使用的。
