### ISSUE TITLE
make error: undefined reference to `Recovery_IsStandby'

### ISSUE THREAD

**Issue by Toknowledge** [Tencent/TBase#6]
gtm_store.c: At top level:
../../../src/include/gtm/standby_utils.h:20:13: warning: inline function ‘Recovery_IsStandby’ declared but never defined
 inline bool Recovery_IsStandby(void);
             ^~~~~~~~~~~~~~~~~~
/usr/bin/ld: main.o: in function `GTM_SigleHandler':
/home/zmeng/Work/OpenProject/TBase/src/gtm/main/main.c:408: undefined reference to `Recovery_IsStandby'
/usr/bin/ld: main.o: in function `main':
/home/zmeng/Work/OpenProject/TBase/src/gtm/main/main.c:946: undefined reference to `Recovery_IsStandby'
/usr/bin/ld: /home/zmeng/Work/OpenProject/TBase/src/gtm/main/main.c:979: undefined reference to `Recovery_IsStandby'
/usr/bin/ld: /home/zmeng/Work/OpenProject/TBase/src/gtm/main/main.c:1013: undefined reference to `Recovery_IsStandby'
/usr/bin/ld: /home/zmeng/Work/OpenProject/TBase/src/gtm/main/main.c:1033: undefined reference to `Recovery_IsStandby'
/usr/bin/ld: main.o:/home/zmeng/Work/OpenProject/TBase/src/gtm/main/main.c:1208: more undefined references to `Recovery_IsStandby' follow

**Comment by waters321** [comment]
我也遇到了这个问题

**Comment by SenHuSelf** [comment]
> 我也遇到了这个问题

请问是在什么平台下编译的？

**Comment by SenHuSelf** [comment]
> 我也遇到了这个问题

请问是在什么平台下编译的？

**Comment by waters321** [comment]
> > 我也遇到了这个问题
> 
> 请问是在什么平台下编译的？

Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-48-generic x86_64)
Linux 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by waters321** [comment]
确实是操作系统的原因，换成centos就可以了

**Comment by weipengffk** [comment]
> 确实是操作系统的原因，换成centos就可以了

我本来就是centos6.7，还是有这个问题

**Comment by caseykwang** [comment]
> > 确实是操作系统的原因，换成centos就可以了
> 
> 我本来就是centos6.7，还是有这个问题

确认一下gcc -v，看一下版本？这个可能是gcc低版本对inline支持的问题。可以把Recovery_IsStandby函数的inline修饰符去掉。

**Comment by caseykwang** [comment]
> 确实是操作系统的原因，换成centos就可以了

能否gcc -v，显示一下当前版本？
