### ISSUE TITLE
alter table test distribute by replication report error: this operation is not permitted

### ISSUE THREAD

**Issue by l1t1** [Tencent/TBase#64]
I run
create table test(a int, b int);
and 
alter table test distribute by replication report 
error: this operation is not permitted
but
create  table test(a int, b int) distribute by replication
 is ok

**Comment by JennyJennyChen** [comment]
Table type: shard table or replication table is specified when the table is created, and cannot be modified later.
If you want to modify the table type, you can delete and rebuild.
