### ISSUE TITLE
insert into a tables with not enough data columns, it should not work, but is inserted

### ISSUE THREAD

**Issue by l1t1** [Tencent/TBase#65]
test=> create table test_in(id int,v1 int,v2 int); -- 3 cols
CREATE TABLE
test=> insert into test_in values(1,2); --2 cols
INSERT 0 1
test=> select * from test_in;
 id | v1 | v2
----+----+----
  1 |  2 |

**Comment by JennyJennyChen** [comment]
column v2 has no insert value, of course it is null. It's  OK!

**Comment by JennyJennyChen** [comment]
User misunderstood
