### ISSUE TITLE
gtm slave再pgxc monitor all 显示not running

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#66]
===============================================================================
gtm 里监控如下：
PGXC monitor all
Running: gtm master
Not running: gtm slave
Running: coordinator master cn001
Running: coordinator master cn002
Running: datanode master dn001
Running: datanode master dn002

===============================================================================
gtm slave 日志如下
1:788518656:2020-08-03 14:02:28.751 CST -LOG:  Connecting the GTM active on gtm:6666...
LOCATION:  gtm_standby_connectToActiveGTM, gtm_standby.c:672
2:788518656:2020-08-03 14:02:28.752 CST -LOG:  Connection established to the GTM active.
LOCATION:  gtm_standby_start_startup, gtm_standby.c:81
3:788518656:2020-08-03 14:02:28.752 CST -LOG:  register standbyhostname datanode1, port number 6666 node name gtmSlave datadir /u01/tbase/data/gtm
LOCATION:  gtm_standby_register_self, gtm_standby.c:321
1:805304064:2020-08-03 14:03:28.758 CST -LOG:  IsValidXLogStatusFile 000000010000000000000002 2
LOCATION:  IsValidXLogStatusFile, main.c:2450
1:767551232:2020-08-03 14:04:26.823 CST -LOG:  Standby is not allowed to connect
LOCATION:  GTMInitConnection, main.c:3746
2:767551232:2020-08-03 14:04:26.823 CST -LOG:  Standby is not allowed to connect
LOCATION:  GTMInitConnection, main.c:3746
3:767551232:2020-08-03 14:04:26.823 CST -LOG:  initiating connection failed
LOCATION:  GTM_ThreadMain, main.c:3105
4:767551232:2020-08-03 14:04:26.823 CST -LOG:  initiating connection failed
LOCATION:  GTM_ThreadMain, main.c:3105
===============================================================================

**Comment by ludongyuan** [comment]
但是主备切换也是可以正常使用的，不明白pgxc里monitor all为什么不行。

**Comment by JennyJennyChen** [comment]
看日志信息gtm slave没有倒换成功，仍然不能连接，怀疑你仍然使用的是老主GTM，想验证倒换成功没有的正确方法是杀掉老主的进程

**Comment by ludongyuan** [comment]
gtm主备切换也是正常的，pgxc_ctl 启动和关闭都没有报错，就是monitor all显示gtm slave not running
