### ISSUE TITLE
pg_dump 备份出错

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#69]
备份脚本：pg_dump -U tbase -d cztjjrp2 -F c -b -v -a -f 1.dump

pg_dump: saving standard_conforming_strings = on
pg_dump: dumping contents of table "dm.t_dmrs_724_1_10"
pg_dump: [archiver (db)] query failed: ERROR:  Error while running COPY
pg_dump: [archiver (db)] query was: COPY dm.t_dmrs_724_1_10 (f2, f3, f4, f5, f6, predict_label) TO stdout;

后台日志报错：coord(5551,10559),"10.0.2.20:52972",5f30e6e9.1593,coord(5551,10559),1,"COPY",2020-08-10 14:19:21 CST,67/4777,0,ERROR,XX000,"start timestamp 970611665294 is too old to execute, recentCommitTs 970815493688",,,,,,"COPY dm.t_dmrs_724_1_10 (f2, f3, f4, f5, f6, predict_label) TO STDOUT",,,"pg_dump"

**Comment by JennyJennyChen** [comment]
The sql (COPY dm.t_dmrs_724_1_10 (f2, f3, f4, f5, f6, predict_label) TO stdout;) running time is too long and is terminated by vacuum, you can adjust the parameters vacuum_delta, eg:
set vacuum_delta = 600; 

600 meaning is 600 second,You can adjust according to the actual situation。

**Comment by ludongyuan** [comment]
解决了，太感谢了。
