### ISSUE TITLE
'COPYRIGHT'  文件被在windows编辑过

### ISSUE THREAD

**Issue by Toknowledge** [Tencent/TBase#7]
Tencent is pleased to support the open source community by making TBase available.  ^M  
^M
Copyright (C) 2019 THL A29 Limited, a Tencent company.  All rights reserved.^M
^M
TBase is licensed under the BSD 3-Clause License, except for the third-party component listed below. ^M
^M
A copy of the BSD 3-Clause License is included in this file.^M
^M
Other dependencies and licenses:^M
^M

**Comment by JennyJennyChen** [comment]
@Toknowledge  已修改，多谢提醒
