### ISSUE TITLE
pgxc_ctl   新增coordinator 失败

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#71]
add coordinator master cn004 datanode4 5432 6667  /u01/tbase/data/coord none none
创建成功，但是无法使用。现在是否支持新增coordinator

**Comment by JennyJennyChen** [comment]
支持新增coordinator，新增后需要修改所有节点的路由，可以参考：
https://github.com/Tencent/TBase/wiki/5%E3%80%81TBase%E7%BB%84%E4%BB%B6%E5%AE%89%E8%A3%85%E5%8F%8A%E7%AE%A1%E7%90%86

**Comment by ludongyuan** [comment]
新增加的cn节点，数据库如何初始呢？
add coordinator master cn004 datanode4 5432 6667 /u01/tbase/data/coord none none这个创建出来的数据库是空的，里面的创建的表结构和数据库都不存在，需要自己从其他cn节点用pg_basebackup复制过来吗，然后再把postgresql.conf配置文件里的pgxc_node_name 参数修改为新的cn004吗？

**Comment by JennyJennyChen** [comment]
新增CN最简单的方法：
1、将某个已有cn001的数据目录物理复制到新加cn004节点
2、然后修改新加的cn004的数据目录下的配置文件的node_name
3、psql连接各个节点添加cn004的路由

**Comment by ludongyuan** [comment]
感谢，结果可以。
