### ISSUE TITLE
tbase 数据库备库同步模式

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#75]
datanode 备库节点是sync
sync_state       | sync
但是把备库停用了，还是继续可以插入数据？

**Comment by ludongyuan** [comment]
postgresql 数据库 sync的时候，备库停用之后，就是不可以插入数据。

**Comment by ludongyuan** [comment]
我还发现 pgxc_ctl  重启之后，之前修改的单节点同步， 又变成异步了。
pgxc_ctl.conf配置文件里datanodeSlaveSync=y，已经修改了。
在postgresq.conf 配置文件里增加了synchronous_standby_names = ''。

**Comment by q2683252** [comment]
确认下主机上的synchronous_standby_names ， synchronous_commit这两个参数。需要这两个参数配合，synchronous_commit是同步的开关，synchronous_standby_names 指定了要同步的备机，如果这个为空，那么也会出现类似异步复制的效果。
