### ISSUE TITLE
message:permission denied for relation (null)

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#76]
2020-08-25 15:32:14.477 CST,"cztjjrp1","cztjjrp1",17249,coord(17249,317),"172.18.85.176:40974",5f44bd60.4361,coord(17249,317),13,"UPDATE",2020-08-25 15:27:28 CST,91/317,77729,
ERROR,42501,"node:dn004, backend_pid:130050, nodename:dn005,backend_pid:65781,message:node:dn002, backend_pid:123114,
 nodename:dn001,backend_pid:105033,message:permission denied for relation (null)",,,,,,
"update T_SYS_TMP_IMPID set f_id3=1 where exists (select 1 from T_RPT_321_4176_2020 where F_COM_ID=f_id1)",,,""

**Comment by JennyJennyChen** [comment]
我这边没问题
postgres=# create table test(id int,name varchar(30),PRIMARY KEY(id));
CREATE TABLE
postgres=# insert into test values(1,'a'),(3,'a'),(5,'a'),(7,'a'),(9,'a'),(11,'a'),(13,'a'),(15,'a');
INSERT 0 8
postgres=# update test set name='b' where exists (select 1);
UPDATE 8
postgres=# create table others(id int,name varchar(30),PRIMARY KEY(id));
CREATE TABLE
postgres=# update test set name='b' where exists (select 1 from others);
UPDATE 0
postgres=# update test set name='b' where exists (select 1 from others where others.id=test.id);
UPDATE 0
postgres=# insert into others values(1,'a'),(3,'a'),(5,'a'),(7,'a'),(9,'a'),(11,'a'),(13,'a'),(15,'a');
INSERT 0 8
postgres=# update test set name='b' where exists (select 1 from others where others.id=test.id);
UPDATE 8
postgres=# 

你的测试用例是啥？

**Comment by ludongyuan** [comment]
我估计这个结果和临时表有关系，问题比较偶然，遇到过几次，但是我也很难重现。

**Comment by q2683252** [comment]
> 我估计这个结果和临时表有关系，问题比较偶然，遇到过几次，但是我也很难重现。

这个在下个版本会修复
