### ISSUE TITLE
vacuumdb错误

### ISSUE THREAD

**Issue by ludongyuan** [Tencent/TBase#77]
vacuumdb: vacuuming of database  failed: ERROR:  node:dn002, backend_pid:107225, nodename:dn003,backend_pid:49855,message:deadlock detected
DETAIL:  Process 49855 waits for AccessShareLock on relation 2601 of database 16394; blocked by process 49933.
Process 49933 waits for RowExclusiveLock on relation 2619 of database 16394; blocked by process 49855.

**Comment by JennyJennyChen** [comment]
按照上面的错误描述，已经知道是49855和49933进程出现了死锁，可通过调用 select pg_terminate_backend(49855)，或者 select pg_terminate_backend(49933)终止掉其中一个进程。
