### ISSUE TITLE
during make -sj error occurs

### ISSUE THREAD

**Issue by javanchueng** [Tencent/TBase#8]
cat: ../../src/interfaces/libpq/objfiles.txt: No such file or directory

during pgxc_ctl init all in progress the following info can be seen:
2019-11-11 10:55:21.307 CST [794] LOG:  could not open file "global/pg_crypt_key.map":No such file or directory for bufFile merging.
2019-11-11 10:55:21.307 CST [794] LOG:  could not open file "global/pg_rel_crypt.map":No such file or directory for bufFile merging.
ALTER NODE coord1 WITH (HOST='host228', PORT=20004, CLUSTER='cluster1');
ERROR:  CLUSTER could not be modified.

EXECUTE DIRECT ON (datanode1) 'ALTER NODE datanode1 WITH (TYPE=''datanode'', HOST=''host228'', PORT=20008, CLUSTER=''cluster1'', PRIMARY, PREFERRED)';
ERROR:  node:datanode1, backend_pid:2870, nodename:datanode1,backend_pid:2870,message:CLUSTER could not be modified.

after installation：
postgres=# select * from pgxc_node;
 node_name | node_type | node_port | node_host | nodeis_primary | nodeis_preferred |   node_id   | node_cluster_name 
-----------+-----------+-----------+-----------+----------------+------------------+-------------+-------------------
 coord1    | C         |      5432 | localhost | f              | f                |  1885696643 | tbase_cluster
 gtm       | G         |     20001 | host227   | t              | f                |   428125959 | tbase_cluster
 coord2    | C         |     20005 | host229   | f              | f                | -1197102633 | cluster1
 datanode1 | D         |     20008 | host228   | t              | t                |   888802358 | cluster1
 datanode2 | D         |     20009 | host229   | f              | f                |  -905831925 | cluster1
(5 rows)

postgres=# create database test;
ERROR:  PGXC Node coord1: object not defined

**Comment by yingtao-wz** [comment]
我也遇到同样的问题，不知道怎么解决。有没有文档呢。

**Comment by javanchueng** [comment]
前面两个错误实际不影响使用，后面那个错误是因为pgxc_ctl在初始化的时候配置文件中的multiCluster=n这个设置，默认是y需要改成n。另外pgxcMainClusterName 、datanodeMasterCluster、coordMasterCluster 这几个配置也要保持一致。

**Comment by yingtao-wz** [comment]
非常感谢，可以啦。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"javanchueng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午4:34
收件人:&nbsp;"Tencent/TBase"<TBase@noreply.github.com&gt;;
抄送:&nbsp;"小卓"<568061750@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/TBase] during make -sj error occurs (#8)




前面两个错误实际不影响使用，后面那个错误是因为pgxc_ctl在初始化的时候配置文件中的multiCluster=n这个设置，默认是y需要改成n。另外pgxcMainClusterName 、datanodeMasterCluster、coordMasterCluster 这几个配置也要保持一致。

**Comment by yingtao-wz** [comment]
这是啥错误呢。感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"javanchueng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午4:34
收件人:&nbsp;"Tencent/TBase"<TBase@noreply.github.com&gt;;
抄送:&nbsp;"小卓"<568061750@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/TBase] during make -sj error occurs (#8)




前面两个错误实际不影响使用，后面那个错误是因为pgxc_ctl在初始化的时候配置文件中的multiCluster=n这个设置，默认是y需要改成n。另外pgxcMainClusterName 、datanodeMasterCluster、coordMasterCluster 这几个配置也要保持一致。
