### ISSUE TITLE
写入测试数据时，表的数据分布突然从2个节点变为1个节点，数据无丢失。多次测试都出现。TBase版本2.1

### ISSUE THREAD

**Issue by softlanguage** [Tencent/TBase#81]
写入测试数据时，表的数据分布突然从2个节点变为1个节点，数据无丢失。多次测试都出现。TBase版本2.1

```
select node_name,node_type,node_host,node_port, * from pgxc_node where node_type='D';
```

![image](https://user-images.githubusercontent.com/65005633/97516478-233ba180-19ce-11eb-954d-06ebda4b6a27.png)

```
SELECT xc_node_id, count(*) FROM t1_pt GROUP BY xc_node_id;
```

![image](https://user-images.githubusercontent.com/65005633/97516514-33538100-19ce-11eb-81e5-9cad899935d6.png)

```sql
-- 建表
create table public.t1_pt
(
f1 int not null,
f2 timestamp not null,
f3 varchar(50),
primary key(f1)
) 
distribute by shard(f1) 
to group default_group;

-- 写入数据
insert into t1_pt (f1, f2, f3)
SELECT generate_series(1001,200000) as f1,
now() as f2, repeat('a',(random()*25)::integer) as order_info;
```

**Comment by q2683252** [comment]
> 表的数据分布突然从2个节点变为1个节点
这个是怎么判断出来的？

**Comment by q2683252** [comment]
> 表的数据分布突然从2个节点变为1个节点

这个是怎么确定出来的？

**Comment by softlang-net** [comment]
环境：2台服务器；


————1
create table public.t1_pt
(
f1 int not null,
f2 timestamp not null,
f3 varchar(50),
primary key(f1)
) 
distribute by shard(f1) 
to group default_group;


——— 2
insert into t1_pt (f1, f2, f3)
SELECT generate_series(1000,100000) as f1,
now() as f2, repeat('a',(random()*25)::integer) as order_info;




——— 3 (此步骤可以重现问题，不行就增加数量、多试几次)
insert into t1_pt (f1, f2, f3)
SELECT generate_series(100001,500000) as f1,
now() as f2, repeat('a',(random()*25)::integer) as order_info;


Best regards,
Yong


On Nov 27, 2020 11:07，q2683252<notifications@github.com> wrote：


表的数据分布突然从2个节点变为1个节点
这个是怎么确定出来的？

**Comment by JennyJennyChen** [comment]
没看懂你的测试方法，可否直接上截图 ，然后说明你怎么看出来的数据分布变了？

**Comment by softlang-net** [comment]
通过sql 可以查看到只有1个节点有数据了：
```
select node_name,node_type,node_host,node_port, * from pgxc_node where node_type='D';
```

**Comment by JennyJennyChen** [comment]
@softlang-net 按照你的方法，测试如下：
![image](https://user-images.githubusercontent.com/48546628/103148575-1f44b980-479c-11eb-9b9e-aa1b70d473eb.png)

并没有出现你说的现象
可否把你的测试截图或者详细情况说一下

**Comment by liuxuc63** [comment]
1. 我使用的服务器配置： 两台4核8G
2. generate_series单次数量加大到200万或更高，如： 
```
insert into t1_pt (f1, f2, f3)
SELECT generate_series(10000,2000000) as f1,
now() as f2, repeat('a',(random()*25)::integer) as order_info;
```

**Comment by JennyJennyChen** [comment]
单次数量加到了300W，还是没有出现
![image](https://user-images.githubusercontent.com/48546628/103185513-b96d4480-48f7-11eb-8313-1f5156d02f21.png)
按照内部原理，这块应该不会出现你说的情况。你还算贴一下截图，我看一下咱们这边的操作情况

**Comment by liuxuc63** [comment]
由于环境已切换为postgresxl，暂无法截图，稍晚点时间再部署一套
