### ISSUE TITLE
执行超时is too old to execute, recentCommitTs 

### ISSUE THREAD

**Issue by zhang750211** [Tencent/TBase#89]
在执行比较大的数据时候，系统提示 is too old to execute, recentCommitTs ，执行时间超过200秒，就会提示这个错误，不知道是什么原因引起的。
错误提示如下:

### Cause: org.postgresql.util.PSQLException: ERROR: node:dn002, backend_pid:22115, nodename:dn002,backend_pid:22115,message:node:dn002, backend_pid:49651, nodename:dn002,backend_pid:49651,message:node:dn002, backend_pid:7699, nodename:dn002,backend_pid:7699,message:start timestamp 10165300657746 is too old to execute, recentCommitTs 10165547841873
; uncategorized SQLException; SQL state [XX000]; error code [0]; ERROR: node:dn002, backend_pid:22115, nodename:dn002,backend_pid:22115,message:node:dn002, backend_pid:49651, nodename:dn002,backend_pid:49651,message:node:dn002, backend_pid:7699, nodename:dn002,backend_pid:7699,message:start timestamp 10165300657746 is too old to execute, recentCommitTs 10165547841873; nested exception is org.postgresql.util.PSQLException: ERROR: node:dn002, backend_pid:22115, nodename:dn002,backend_pid:22115,message:node:dn002, backend_pid:49651, nodename:dn002,backend_pid:49651,message:node:dn002, backend_pid:7699, nodename:dn002,backend_pid:7699,message:start timestamp 10165300657746 is too old to execute, recentCommitTs 10165547841873}

**Comment by JennyJennyChen** [comment]
调整一下vacuum_delta参数就行，参考下：
https://github.com/Tencent/TBase/issues/84

**Comment by zhang750211** [comment]
好的，我设置测试一下，非常感谢！
