### ISSUE TITLE
Suggest to add more introductions for this product

### ISSUE THREAD

**Issue by ballenwen** [Tencent/TBase#9]
1. Product Positioning:  I have a little doubt about this product positioning, if it is for users around the world, the introduction in index page (README.md) should be more professional, which do not mix  English and Chinese description together, and consider more from user's perspectives. 

2. Solution:  The official website (tbase.qq.com) hasn't been update too long since 2017,  I see there are many customers using it . So I hope the website can update more customer's solution and let more people to know what TBase can do and How to introduce TBase in their businesses.

Thank you

**Comment by JennyJennyChen** [comment]
@ballenwen 
Thank you for your advice.

1. revised
2. Content is being redesigned and updated, please wait
