### ISSUE TITLE
请问一下tbase怎么更新pg内核的版本呢

### ISSUE THREAD

**Issue by BerkeleyLL** [Tencent/TBase#90]

**Comment by JennyJennyChen** [comment]
TBase会根据自己的产品规划，直接修改代码，在代码中合入一些PG内核的新版本特性

**Comment by yazun** [comment]
Hello,
Any news on the timeline for an eventual PG kernel update?
Cheers

**Comment by JennyJennyChen** [comment]
> Hello,
> Any news on the timeline for an eventual PG kernel update?
> Cheers

Stored procedures and partition table related features, is expected by mid-year update to PG12
Thank you!

**Comment by yazun** [comment]
Fantastic news! We cannot wait for partition-wise join improvements!
