### ISSUE TITLE
pgxc_node系统表可泄露数据库集群所有节点的ip和port

### ISSUE THREAD

**Issue by 23R3F** [Tencent/TBase#95]
如题，pgxc_node存储了cn和dn的ip与port，任意普通用户可以读取，外部攻击者获取这些信息后可推测内网ip规划，集群节点规模，使用内网扫描工具可以获取节点的更多信息，这样有利于攻击者进行渗透攻击

不知道这种算不算一个安全问题，从个人理解来说，对于一个分布式的集群数据库来说，不应该暴露所有集群节点的ip，应该是只需要提供必要的一个cn节点ip就行了，毕竟暴露的越多越容易产生安全问题

**Comment by JennyJennyChen** [comment]
多谢建议，我们已经添加到需求列表中，会有专人根据需求优先级进行排期

**Comment by JennyJennyChen** [comment]
已解决，参考commit ea325d947fcd5a4037fc2d41d45ffc5d95585599
