### ISSUE TITLE
MLS_TRANSPARENT_CRYPT_ALGORITHM_BIND_TABLE

### ISSUE THREAD

**Issue by hujinnvshi** [Tencent/TBase#96]
在腾讯提供的学习手册6.8节中提到的方法MLS_TRANSPARENT_CRYPT_ALGORITHM_BIND_TABLE 没有搜索到,请问该方法的放置位置.

**Comment by JennyJennyChen** [comment]
这是透明加密部分，是安全相关的特性，只有商业版本才具有此功能。开源版本不具备此能力
